### ISSUE TITLE
Exception with .netstandard 1.4

### ISSUE THREAD

**Issue by amoraitis** [dncuug/X.Web.RSS#5]
I have a project [here](https://github.com/amoraitis/EclassMobileApi) with project configuration set to .netstandard1.4, because i want to target Universal Windows Platform from my library. It seems that an exception throws on `var rssDocument = RssDocument.Load(rss);` (with Windows.Web.SyndicationFeed it runs perfectly with the same **strings**)
`Exception thrown: 'System.InvalidOperationException' in System.Private.Xml.dll
An exception of type 'System.InvalidOperationException' occurred in System.Private.Xml.dll but was not handled in user code
There is an error in XML document (1, 529).`
#### Details
```
System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (1, 529).
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at X.Web.RSS.RssDocument.Load(Stream source)
   at X.Web.RSS.RssDocument.Load(String xml)
   at EclassApi.ViewModel.AnnouncementViewModel.<SetAnouncements>d__12.MoveNext() in C:\Users\τασος\Source\Repos\EclassMobileApi\EclassApi\AnnouncementViewModel.cs:line 45

Inner Exception 1:
NotSupportedException: Setting this property is not supported
```

**Comment by ernado-x** [comment]
Could you please provide url, or content of RSS feed which you try load?

**Comment by ernado-x** [comment]
Please check new version https://www.nuget.org/packages/xwebrss/2.2.0 and open this ticket if you will have same problem in future

**Comment by amoraitis** [comment]
Thank you, amazing support. It works with the update!
